title: M. Farhan Rais
logo: /assets/img/headshot.jpg
description: >
  After 10 years conducting training in the Army, I am proficient at analysis using Microsoft Excel, Power BI, Access and Qlik. My strong desire to grow and learn was evident in the 7 roles undertaken in the Army. Transiting into data science, I hold academic background in information systems from SIM-UOL for undergraduate studies, specialist certificate in computing from NUS-SCALE and data science and analytics from General Assembly. Fluent in Python, C++, SQL and with experience in statistical modelling, supervised/unsupervised learning, computer vision and Tableau.

  <br><br>
  <a href="https://www.linkedin.com/in/mfarhanrais/">View My LinkedIn Profile</a> 
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: G-Q6LE3C48N6
